apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-04-11T16:49:23Z
  name: intro.dev.hillghost.com
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://kops-blog/intro.dev.hillghost.com
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-2a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-2a
      name: a
    name: events
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.5.6
  masterInternalName: api.internal.intro.dev.hillghost.com
  masterPublicName: api.intro.dev.hillghost.com
  networkCIDR: 172.20.0.0/16
  networkID: vpc-6d8c0c04
  networking:
    weave: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.16.0/24
    egress: nat-0d057636efddd295b
    name: us-east-2a
    type: Private
    zone: us-east-2a
  - cidr: 172.20.17.0/24
    egress: nat-09cec8ea68ca86c7b
    name: us-east-2b
    type: Private
    zone: us-east-2b
  - cidr: 172.20.18.0/24
    egress: nat-0de24c618fbf116d1
    name: us-east-2c
    type: Private
    zone: us-east-2c
  - cidr: 172.20.20.0/24
    name: utility-us-east-2a
    type: Utility
    zone: us-east-2a
  - cidr: 172.20.21.0/24
    name: utility-us-east-2b
    type: Utility
    zone: us-east-2b
  - cidr: 172.20.22.0/24
    name: utility-us-east-2c
    type: Utility
    zone: us-east-2c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-04-11T16:49:24Z
  labels:
    kops.k8s.io/cluster: intro.dev.hillghost.com
  name: nodes
spec:
  image: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2017-01-09
  machineType: t2.medium
  maxSize: 3
  minSize: 3
  role: Node
  subnets:
  - us-east-2a
  - us-east-2b
  - us-east-2c
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-04-11T16:49:23Z
  labels:
    kops.k8s.io/cluster: intro.dev.hillghost.com
  name: master-us-east-2a
spec:
  image: kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2017-01-09
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-2a
